# Generated by Django 5.0.7 on 2024-07-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_temporarypassword_delete_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Media',
                'unique_together': {('name',)},
            },
        ),
    ]
